# Generated by Django 6.0.3 on 2026-03-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("project", "Project Collaboration"),
                    ("discussion", "Discussion Forum"),
                ],
                default="project",
                max_length=20,
            ),
        ),
    ]
